# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', jsonfield.fields.JSONField(default=None, verbose_name='\u0410\u0432\u0442\u043e\u0431\u0443\u0441')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0427\u0435\u043b\u043e\u0432\u0435\u043a')),
            ],
            options={
                'verbose_name': '\u0410\u0432\u0442\u043e\u0431\u0443\u0441',
                'verbose_name_plural': '\u0410\u0432\u0442\u043e\u0431\u0443\u0441',
            },
        ),
    ]
