# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ('-dt',),
                'verbose_name': '\u0410\u0434\u043c\u0438\u043d\u0441\u043a\u0430\u044f \u043d\u043e\u0432\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0410\u0434\u043c\u0438\u043d\u0441\u043a\u0438\u0435 \u043d\u043e\u0432\u043e\u0441\u0442\u0438',
            },
        ),
    ]
