# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=0, verbose_name='\u0412\u043d\u0435\u0441\u0435\u043d\u043d\u0430\u044f \u043e\u043f\u043b\u0430\u0442\u0430'),
        ),
    ]
