# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields
import yafotki.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f \u0418\u043c\u044f')),
                ('year', models.IntegerField(verbose_name='\u0413\u043e\u0434 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('fatherland', models.CharField(max_length=255, verbose_name='\u041c\u0435\u0441\u0442\u043e \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('description', redactor.fields.RedactorField(verbose_name='\u041e\u0431\u0449\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f')),
                ('secret', redactor.fields.RedactorField(verbose_name='\u0421\u043a\u0435\u043b\u0435\u0442 \u0432 \u0448\u043a\u0430\u0444\u0443')),
                ('work', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='\u041c\u0435\u0441\u0442\u043e \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('conviction', redactor.fields.RedactorField(blank=True, default=None, null=True, verbose_name='\u0421\u0443\u0434\u0438\u043c\u043e\u0441\u0442\u044c')),
                ('quest', redactor.fields.RedactorField(verbose_name='\u041a\u0432\u0435\u043d\u0442\u0430')),
                ('face', yafotki.fields.YFField(blank=True, default=None, max_length=255, null=True, upload_to='default', verbose_name='\u0424\u043e\u0442\u043e \u0432 \u0444\u0430\u0441')),
                ('halfface', yafotki.fields.YFField(blank=True, default=None, max_length=255, null=True, upload_to='default', verbose_name='\u0424\u043e\u0442\u043e \u0432 \u043f\u0440\u043e\u0444\u0438\u043b\u044c')),
                ('is_locked', models.BooleanField(default=False, help_text='\u041c\u043e\u0436\u043d\u043e \u043b\u0438 \u0447\u0435\u043b\u043e\u0432\u0435\u043a\u0443 \u0440\u0435\u0434\u0430\u043a\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u0440\u043e\u043b\u044c', verbose_name='\u0417\u0430\u043c\u043e\u0440\u043e\u0436\u0435\u043d\u0430')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0420\u043e\u043b\u044c',
                'verbose_name_plural': '\u0420\u043e\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='RoleConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('is_locked', models.BooleanField(default=False, verbose_name='\u0417\u0430\u043c\u043e\u0440\u043e\u0436\u0435\u043d\u043e')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='rpg.Role', verbose_name='\u0420\u043e\u043b\u044c')),
                ('role_rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_connections', to='rpg.Role', verbose_name='\u0421\u0432\u044f\u0437\u0430\u043d\u043d\u0430\u044f \u0440\u043e\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u0432\u044f\u0437\u044c \u0440\u043e\u043b\u0435\u0439',
                'verbose_name_plural': '\u0421\u0432\u044f\u0437\u0438 \u0440\u043e\u043b\u0435\u0439',
            },
        ),
    ]
