# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='conviction',
        ),
        migrations.RemoveField(
            model_name='role',
            name='face',
        ),
        migrations.RemoveField(
            model_name='role',
            name='fatherland',
        ),
        migrations.RemoveField(
            model_name='role',
            name='halfface',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.RemoveField(
            model_name='role',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='role',
            name='work',
        ),
        migrations.RemoveField(
            model_name='role',
            name='year',
        ),
        migrations.AddField(
            model_name='role',
            name='age',
            field=models.IntegerField(default=0, verbose_name='\u0412\u043e\u0437\u0440\u0430\u0441\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='character_1',
            field=models.CharField(blank=True, choices=[('1', '\u041c\u0430\u043a\u0430\u0440\u0435\u0432'), ('2', '\u0421\u0442\u0435\u0441\u0441\u0435\u043b\u044c')], default=None, max_length=255, null=True, verbose_name='\u041c\u0430\u043a\u0430\u0440\u0435\u0432 / \u0421\u0442\u0435\u0441\u0441\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='role',
            name='character_2',
            field=models.CharField(blank=True, choices=[('1', '\u0412\u043e\u0440'), ('2', '\u0447\u0435\u0441\u0442\u043d\u044b\u0439')], default=None, max_length=255, null=True, verbose_name='\u0412\u043e\u0440 / \u0447\u0435\u0441\u0442\u043d\u044b\u0439'),
        ),
        migrations.AddField(
            model_name='role',
            name='character_3',
            field=models.CharField(blank=True, choices=[('1', '\u0410\u043d\u0433\u043b\u043e\u0444\u0438\u043b\u044b'), ('2', '\u0440\u0443\u0441\u043e\u0444\u043e\u0431\u044b')], default=None, max_length=255, null=True, verbose_name='\u0410\u043d\u0433\u043b\u043e\u0444\u0438\u043b\u044b / \u0440\u0443\u0441\u043e\u0444\u043e\u0431\u044b'),
        ),
        migrations.AddField(
            model_name='role',
            name='character_4',
            field=models.CharField(blank=True, choices=[('1', '\u0420\u0435\u0432\u043e\u043b\u044e\u0446\u0438\u043e\u043d\u0435\u0440\u044b'), ('2', '\u043c\u043e\u043d\u0430\u0440\u0445\u0438\u0441\u0442\u044b')], default=None, max_length=255, null=True, verbose_name='\u0420\u0435\u0432\u043e\u043b\u044e\u0446\u0438\u043e\u043d\u0435\u0440\u044b/\u043c\u043e\u043d\u0430\u0440\u0445\u0438\u0441\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='role',
            name='character_5',
            field=models.CharField(blank=True, choices=[('1', '\u0420\u043e\u0441\u0441\u0438\u044f'), ('2', '\u042f\u043f\u043e\u043d\u0438\u044f')], default=None, max_length=255, null=True, verbose_name='\u0420\u043e\u0441\u0441\u0438\u044f/\u042f\u043f\u043e\u043d\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='role',
            name='family_state',
            field=models.CharField(choices=[('married', '\u0436\u0435\u043d\u0430\u0442/\u0437\u0430\u043c\u0443\u0436\u0435\u043c'), ('date', '\u0435\u0441\u0442\u044c \u0441\u0435\u0440\u0434\u0435\u0447\u043d\u044b\u0439 \u0434\u0440\u0443\u0433'), ('widower', '\u0432\u0434\u043e\u0432\u0435\u0446/\u0432\u0434\u043e\u0432\u0430'), ('alone', '\u0441\u0435\u0440\u0434\u0435\u0447\u043d\u043e\u0439 \u043f\u0440\u0438\u0432\u044f\u0437\u0430\u043d\u043d\u043e\u0441\u0442\u0438 \u043d\u0435\u0442'), ('none', '\u0432\u0441\u0435 \u0441\u043b\u043e\u0436\u043d\u043e')], default='none', max_length=255, verbose_name='\u0421\u0435\u043c\u0435\u0439\u043d\u043e\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='\u0418\u043c\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='middle_name',
            field=models.CharField(default='', max_length=255, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='military',
            field=models.CharField(blank=True, choices=[('army', '\u0410\u0440\u043c\u0438\u044f'), ('navy', '\u0424\u043b\u043e\u0442')], default=None, max_length=255, null=True, verbose_name='\u0412\u043e\u0435\u043d\u043d\u044b\u0439'),
        ),
        migrations.AddField(
            model_name='role',
            name='party',
            field=models.CharField(blank=True, choices=[('war', '\u041f\u0430\u0440\u0442\u0438\u044f \u0432\u043e\u0439\u043d\u044b'), ('peace', '\u041f\u0430\u0440\u0442\u0438\u044f \u043c\u0438\u0440\u0430')], default=None, max_length=255, null=True, verbose_name='\u041f\u0430\u0440\u0442\u0438\u044f'),
        ),
        migrations.AddField(
            model_name='role',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='\u0422\u0438\u0442\u0443\u043b/\u0437\u0432\u0430\u043d\u0438\u0435'),
            preserve_default=False,
        ),
    ]
