# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_auto_20160601_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='character_1',
            field=models.CharField(blank=True, choices=[('1', '\u041c\u0430\u043a\u0430\u0440\u043e\u0432'), ('2', '\u0421\u0442\u0435\u0441\u0441\u0435\u043b\u044c')], default=None, max_length=255, null=True, verbose_name='\u041c\u0430\u043a\u0430\u0440\u043e\u0432 / \u0421\u0442\u0435\u0441\u0441\u0435\u043b\u044c'),
        ),
        migrations.AlterField(
            model_name='role',
            name='character_3',
            field=models.CharField(blank=True, choices=[('1', '\u0410\u043d\u0433\u043b\u043e\u0444\u0438\u043b\u044b'), ('2', '\u0420\u0443\u0441\u043e\u0444\u0438\u043b\u044b')], default=None, max_length=255, null=True, verbose_name='\u0410\u043d\u0433\u043b\u043e\u0444\u0438\u043b\u044b / \u0420\u0443\u0441\u043e\u0444\u0438\u043b\u044b'),
        ),
        migrations.AlterField(
            model_name='role',
            name='character_4',
            field=models.CharField(blank=True, choices=[('1', '\u0420\u0435\u0432\u043e\u043b\u044e\u0446\u0438\u043e\u043d\u0435\u0440\u044b'), ('2', '\u041c\u043e\u043d\u0430\u0440\u0445\u0438\u0441\u0442\u044b')], default=None, max_length=255, null=True, verbose_name='\u0420\u0435\u0432\u043e\u043b\u044e\u0446\u0438\u043e\u043d\u0435\u0440\u044b/\u043c\u043e\u043d\u0430\u0440\u0445\u0438\u0441\u0442\u044b'),
        ),
    ]
